#!/usr/bin/env bash
# Generate the Homebrew formula for a published release.
#
# The formula must carry a sha256 per platform, so it can only be written after the release
# assets exist. This reads the SHA256SUMS published by .github/workflows/release.yml rather
# than re-hashing downloads locally, so the formula always matches what CI actually built.
#
# Usage:
#   packaging/homebrew/update-formula.sh v2.0.0 > skillspector-quality.rb
#   packaging/homebrew/update-formula.sh v2.0.0 ~/src/homebrew-tap/Formula/skillspector-quality.rb
set -euo pipefail

TAG="${1:?usage: update-formula.sh <tag> [output-file]}"
OUT="${2:-}"
REPO="${REPO:-larsroettig/skillspector-quality}"
VERSION="${TAG#v}"

# SHA256SUMS_FILE lets the generator run against a local checksum file — used by the test in
# tests/test_packaging.py to validate the emitted Ruby without needing a published release.
if [ -n "${SHA256SUMS_FILE:-}" ]; then
  SUMS="$(cat "$SHA256SUMS_FILE")"
else
  SUMS="$(curl -fsSL "https://github.com/${REPO}/releases/download/${TAG}/SHA256SUMS")"
fi

# Pull the digest for one asset out of the published SHA256SUMS file.
digest() {
  local target="$1" name line
  name="skillspector-quality-${VERSION}-${target}.tar.gz"
  line="$(printf '%s\n' "$SUMS" | grep -F "$name" || true)"
  if [ -z "$line" ]; then
    echo "error: no checksum for ${name} in ${TAG} SHA256SUMS" >&2
    exit 1
  fi
  printf '%s' "$line" | awk '{print $1}'
}

ARM64_SHA="$(digest darwin-arm64)"
X86_SHA="$(digest darwin-x86_64)"
LINUX_SHA="$(digest linux-x86_64)"

read -r -d '' FORMULA <<RUBY || true
# Generated by packaging/homebrew/update-formula.sh — do not hand-edit the digests.
class SkillspectorQuality < Formula
  desc "Deterministic authoring quality scorer for Claude Code skills"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  # Ships a prebuilt binary rather than a Python virtualenv formula: the runtime tree is 48
  # packages (six of them Rust/C extensions) and its core dependency, skillspector, is not on
  # PyPI — so there is nothing for \`brew update-python-resources\` to resolve against.
  on_macos do
    on_arm do
      url "https://github.com/${REPO}/releases/download/${TAG}/skillspector-quality-${VERSION}-darwin-arm64.tar.gz"
      sha256 "${ARM64_SHA}"
    end
    on_intel do
      url "https://github.com/${REPO}/releases/download/${TAG}/skillspector-quality-${VERSION}-darwin-x86_64.tar.gz"
      sha256 "${X86_SHA}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/${REPO}/releases/download/${TAG}/skillspector-quality-${VERSION}-linux-x86_64.tar.gz"
      sha256 "${LINUX_SHA}"
    end
  end

  def install
    bin.install "skillspector-quality"
  end

  test do
    assert_match "skillspector-quality", shell_output("#{bin}/skillspector-quality --help")

    # Scores a minimal skill end to end. Asserts a real number comes back, which fails loudly
    # if the frozen bundle lost a dynamically imported dependency.
    (testpath/"my-skill").mkpath
    (testpath/"my-skill/SKILL.md").write <<~MARKDOWN
      ---
      name: brew-smoke-test
      description: Verify the installed binary scores a skill. Use when testing the formula.
      ---

      # Brew Smoke Test

      Confirms the Homebrew build scores a skill bundle without a Python environment present.
    MARKDOWN

    output = shell_output("#{bin}/skillspector-quality scan #{testpath}/my-skill --no-llm --format json")
    assert_match(/"score":\\s*\\d+/, output)
  end
end
RUBY

if [ -n "$OUT" ]; then
  printf '%s\n' "$FORMULA" > "$OUT"
  echo "wrote $OUT" >&2
else
  printf '%s\n' "$FORMULA"
fi
