name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@52ecc61cb587ee99c26825a112a21abf19c7448c # main
        with:
          language: python

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@52ecc61cb587ee99c26825a112a21abf19c7448c # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 30
          mode: code-change
          language: python
